### ISSUE TITLE
org.nutz.lang.born.BorningException: Fail to born 'com.jarvis.cache.redis.ShardedCachePointCut'

### ISSUE THREAD

**Issue by zhongkaiuu** [qiujiayu/AutoLoadCache-nutz#3]
Caused by: org.nutz.lang.born.BorningException: Fail to born 'com.jarvis.cache.redis.ShardedCachePointCut'
 by args: [
  @(com.jarvis.cache.to.AutoLoadConfig@4c6e276e)]
    at org.nutz.lang.Mirror.getBorning(Mirror.java:954)
    at org.nutz.ioc.impl.ObjectMakerImpl.make(ObjectMakerImpl.java:107)
    ... 17 more

把AutoLoadCache-nutz加入报这错，dao.js里的cachePointCut args配置只需要autoLoadConfig？我看ShardedCachePointCut是有3个参数的构造器。不知提供的信息是否足够，如果描述不清楚请联系zhongkaiuu@gmail.com

**Comment by qiujiayu** [comment]
这个是因为使用AutoLoadCache版本的问题，如果用最新版本的AutoLoadCache的话，就需要使用3个参数。
